import csv
import importlib.util
import io
import tempfile
import unittest
from pathlib import Path
from contextlib import redirect_stdout


ROOT = Path(__file__).parents[1]


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


WIN = load("win_analyze", ROOT / "skills/disk-space-analyzer/scripts/windows/analyze_disk.py")
MAC = load("mac_analyze", ROOT / "skills/disk-space-analyzer/scripts/macos/analyze_disk.py")


class P0Tests(unittest.TestCase):
    def test_size_units_are_strict_and_binary(self):
        for module in (WIN, MAC):
            self.assertEqual(module.parse_size("1KB"), 1024)
            self.assertEqual(module.parse_size("1.5 GB"), 1610612736)
            with self.assertRaises(ValueError):
                module.parse_size("1XB")

    def test_protected_and_rebuildable_paths(self):
        rows = [
            ["Generated by WizTree 4.32", "", "", "", "", "", ""],
            ["File Name", "Size", "Allocated", "Modified", "Attributes", "Files", "Folders"],
            [r"C:\repo\.git\objects\a", "1", "4096", "", "A", "0", "0"],
            [r"C:\repo\.idea\workspace.xml", "1", "4096", "", "A", "0", "0"],
            [r"C:\repo\node_modules\x.js", "1", "4096", "", "A", "0", "0"],
            [r"C:\Users\u\.ollama\models\blob", "1", "8192", "", "A", "0", "0"],
            [r"C:\Temp\x.tmp", "1", "2048", "", "A", "0", "0"],
        ]
        with tempfile.NamedTemporaryFile("w", encoding="utf-8-sig", newline="", suffix=".csv", delete=False) as f:
            csv.writer(f).writerows(rows)
            path = f.name
        items = WIN.read_csv(path)
        with redirect_stdout(io.StringIO()):
            result = WIN.cmd_cleanable(items)
        self.assertNotIn("C:\\repo\\.git\\objects\\a", [x["path"] for v in result["categories"].values() for x in v["sample_files"]])
        self.assertNotIn("C:\\repo\\.idea\\workspace.xml", [x["path"] for v in result["categories"].values() for x in v["sample_files"]])
        self.assertEqual(result["categories"]["dev"]["safety"], "check")
        self.assertEqual(result["categories"]["cache"]["safety"], "check")
        self.assertEqual(result["total_cleanable_bytes"], 14336)
        self.assertEqual(result["total_cleanable_logical_bytes"], 3)

    def test_macos_protects_metadata_and_requires_confirmation(self):
        items = [
            {"path": "/repo/.git/objects/a", "size": 1, "allocated": 4096, "is_dir": False},
            {"path": "/repo/.idea/workspace.xml", "size": 1, "allocated": 4096, "is_dir": False},
            {"path": "/repo/node_modules/x.js", "size": 1, "allocated": 4096, "is_dir": False},
            {"path": "/Users/u/.ollama/models/blob", "size": 1, "allocated": 8192, "is_dir": False},
        ]
        with redirect_stdout(io.StringIO()):
            result = MAC.cmd_cleanable(items)
        self.assertEqual(len(result["protected_advisories"]), 2)
        self.assertEqual(result["categories"]["dev"]["safety"], "check")
        self.assertEqual(result["categories"]["cache"]["safety"], "check")
        self.assertEqual(result["total_cleanable_bytes"], 12288)


if __name__ == "__main__":
    unittest.main()
